var searchData=
[
  ['direct_20memory_20access_20_28dma_29',['Direct Memory Access (DMA)',['../group__dma.html',1,'']]],
  ['dma_5fcnt',['DMA_CNT',['../group___d_m_a___c_n_t.html',1,'']]],
  ['dma_5fcntrld',['DMA_CNTRLD',['../group___d_m_a___c_n_t_r_l_d.html',1,'']]],
  ['dma_5fctrl',['DMA_CTRL',['../group___d_m_a___c_t_r_l.html',1,'']]],
  ['dma_5fdst',['DMA_DST',['../group___d_m_a___d_s_t.html',1,'']]],
  ['dma_5fdstrld',['DMA_DSTRLD',['../group___d_m_a___d_s_t_r_l_d.html',1,'']]],
  ['dma_5finten',['DMA_INTEN',['../group___d_m_a___i_n_t_e_n.html',1,'']]],
  ['dma_5fintfl',['DMA_INTFL',['../group___d_m_a___i_n_t_f_l.html',1,'']]],
  ['dma_5fregisters',['DMA_Registers',['../group__dma__registers.html',1,'']]],
  ['dma_5fsrc',['DMA_SRC',['../group___d_m_a___s_r_c.html',1,'']]],
  ['dma_5fsrcrld',['DMA_SRCRLD',['../group___d_m_a___s_r_c_r_l_d.html',1,'']]],
  ['dma_5fstatus',['DMA_STATUS',['../group___d_m_a___s_t_a_t_u_s.html',1,'']]],
  ['dvs_5fadj_5fdwn',['DVS_ADJ_DWN',['../group___d_v_s___a_d_j___d_w_n.html',1,'']]],
  ['dvs_5fadj_5fup',['DVS_ADJ_UP',['../group___d_v_s___a_d_j___u_p.html',1,'']]],
  ['dvs_5fctl',['DVS_CTL',['../group___d_v_s___c_t_l.html',1,'']]],
  ['dvs_5fdirect',['DVS_DIRECT',['../group___d_v_s___d_i_r_e_c_t.html',1,'']]],
  ['dvs_5fmon',['DVS_MON',['../group___d_v_s___m_o_n.html',1,'']]],
  ['dvs_5fregisters',['DVS_Registers',['../group__dvs__registers.html',1,'']]],
  ['dvs_5fstat',['DVS_STAT',['../group___d_v_s___s_t_a_t.html',1,'']]],
  ['dvs_5ftap_5fsel',['DVS_TAP_SEL',['../group___d_v_s___t_a_p___s_e_l.html',1,'']]],
  ['dvs_5fthres_5fcmp',['DVS_THRES_CMP',['../group___d_v_s___t_h_r_e_s___c_m_p.html',1,'']]],
  ['delay_20utility_20functions',['Delay Utility Functions',['../group___m_x_c__delay.html',1,'']]]
];
