/* AUTOGENERATED, DO NOT EDIT */

#ifndef _BUILD_INFO_H_
#define _BUILD_INFO_H_

#define S_BUILD_NUMBER 0
#define S_BUILD_TYPE "unknown"
#define S_BUILD_MACHINE "unknown"
#define S_BUILD_TIMESTAMP "unknown"
#define S_BUILD_SCM_BRANCH "unknown"
#define S_BUILD_SCM_REVISION "unknown"

#endif /* _BUILD_INFO_H_ */
